name: playwright_latest

on:
  push:
    branches: [ "main" ]
    paths: [ 'jdk-21/**' ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./jdk-21
          tags: sleodlx/jdk-21-mvn-node-playwright:latest
          push: true
